### PR TITLE
updated api_spec.json to use newer paginations

### PR DESCRIPTION
**Pull request by aq1018**
@DavidHuie @3dna/web-services

### CODE REVIEW

**Comment by Jacobkg** [comment]
Something isn't right here:

2,151 additions and 2,471 deletions.

**Comment by DavidHuie** [comment]
Does this just affect the signups API?

**Comment by aq1018** [comment]
Welll... this is the generated json copied straight from https://github.com/3dna/api_explorer/blob/aq1018/pagination_update/public/data/nationbuilder.json

**Comment by aq1018** [comment]
It affects all list endpoints that uses pagination.

**Comment by aq1018** [comment]
@Jacobkg Maybe looking at [this PR](https://github.com/3dna/api_explorer/pull/5/files) will actually be easier to asses what has been done. Basically, the changes from the link above gets compiled into a giant `JSON` file, and that gets copied here...

**Comment by aq1018** [comment]
@Jacobkg @DavidHuie So, my editor was auto formatting JSON files. Disabled this feature, and now diffs show up!

**Comment by Jacobkg** [comment]
@aq1018 Can you either rebase or make a new branch/pr with a clean commit?

**Comment by aq1018** [comment]
I'll do a rebase + force push

**Comment by aq1018** [comment]
@Jacobkg force pushed a clean commit.

**Comment by aq1018** [comment]
Also we might want to version it as 1.0.0

If you want new pagination:  `>=1.0.0`
If you want old pagination: `~> 0.8.0`

In `1.0.0` we also probably want to wrap response objects and add `next_page` and `prev_page` methods for people to paginate with.

**Comment by DavidHuie** [comment]
Bumping it up to 1.0 is probably fine. If we choose to implement the fancy pagination, we could always bump the version up to 2.0.

**Comment by aq1018** [comment]
Yeah, I think we should implement fancy pagination in next release. For now we can just ship this.

**Comment by aq1018** [comment]
@3dna/web-services Am I good to go on this one?

**Comment by DavidHuie** [comment]
I don't see the version bump on here.

**Comment by aq1018** [comment]
I think make version bump on master is better. Branches should only be concerned with the actual code changes.

**Comment by aq1018** [comment]
a release could also have many PRs.

**Pull request merged**
